openapi: 3.0.1
info:
  title: Multiversx Developer Plugin
  description: Compile and deploy Multiversx smart contracts.
  version: v0
servers:
  - url: http://localhost:8000/api
paths:
  /compile:
    post:
      operationId: compileContract
      summary: Compile a Rust smart contract for Multiversx
      description: Compile a Rust smart contracts designed for Multiversx (previously Elrond). Provide the source code as a string.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - source
              properties:
                source:
                  type: string
                  description: Rust source code of the smart contract.
      responses:
        '200':
          description: Contract compiled successfully or an error message if compilation failed.
          content:
            text/plain:
              schema:
                type: string
  /deploy:
    get:
      operationId: deployContract
      summary: Deploy a smart contract to Multiversx
      description: Deploy the most recent smart contract to Multiversx (previously Elrond) that has been compiled.
      responses:
        '200':
          description: Contract deployed successfully or an error message if deployment failed.
          content:
            text/plain:
              schema:
                type: string
